name: Auto Market Scan

on:
  schedule:
    # Pre-open scan at 09:00 Toronto = 13:00 UTC (Mon–Fri)
    - cron: "0 13 * * 1-5"
    # Every 15 min during market hours 09:30–16:00 Toronto = 13:30–20:00 UTC (Mon–Fri)
    - cron: "*/15 13-20 * * 1-5"
  workflow_dispatch: {}   # lets you trigger manually if needed

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Wake & run scan (pre-open)
        if: ${{ startsWith(github.event.schedule, '0 13') || github.event_name == 'workflow_dispatch' }}
        run: |
          curl -fsSL https://stock-watch-uqc1.onrender.com/scan/preopen || exit 0
      - name: Live scan during market hours
        if: ${{ startsWith(github.event.schedule, '*/15') || github.event_name == 'workflow_dispatch' }}
        run: |
          curl -fsSL https://stock-watch-uqc1.onrender.com/scan || exit 0
